version: "3.9"
services:

  db:
    image: postgres:15-alpine
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
